# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "Command-line TOON/JSON processor — jq for TOON"
  homepage "https://github.com/tq-lang/tq"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0/tq_0.1.0_darwin_amd64.tar.gz"
      sha256 "2f69feedf9bc8fb02f76d2231a55e8858eead8763be40c9bc0e3f1d6772b7430"

      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0/tq_0.1.0_darwin_arm64.tar.gz"
      sha256 "46b93bf31f81bd9f6e378c470b2514905ec098911f1df4dd01526f302c5d6b32"

      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0/tq_0.1.0_linux_amd64.tar.gz"
      sha256 "36aae4797b1ac6e530dd5a3fa9e265ff85c171ef27e34cd1877f6ca5bce15b03"
      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0/tq_0.1.0_linux_arm64.tar.gz"
      sha256 "b1d3b27e4aa0d71c3f229e390d7c94cf132363e8d4921a525356a118d45540f6"
      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tq --version")
  end
end
