# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "Command-line TOON/JSON processor — jq for TOON"
  homepage "https://github.com/tq-lang/tq"
  version "0.1.0-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc1/tq_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "0fb617c69eea4c74d21c8844696e599c8d959f18b7df83ee3bddd515b9a299de"

      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc1/tq_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "6bbe395e275cfb607918e128d4c20fca5003eb1bad1d96b042faf79881cf99f0"

      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc1/tq_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "2f99968e258841def1a9096193ade46d15e48728c38bd692604d357a8946b4c9"
      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc1/tq_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "f609d05aac8fc7283944e820d69cb6623a1da029d164cf6bc77a128654d5eb5d"
      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tq --version")
  end
end
