# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tq < Formula
  desc "Command-line TOON/JSON processor — jq for TOON"
  homepage "https://github.com/tq-lang/tq"
  version "0.1.0-rc10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc10/tq_0.1.0-rc10_darwin_amd64.tar.gz"
      sha256 "9f1969f5364394a6f4f86c623a086860d8d6ce1a496099258a10a4cb3453648a"

      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc10/tq_0.1.0-rc10_darwin_arm64.tar.gz"
      sha256 "afafb112ff53a18a700145d622a82d40aa4945aa14bce477f07fbafb1349ba02"

      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc10/tq_0.1.0-rc10_linux_amd64.tar.gz"
      sha256 "c5c8a66655573cf71cb874e5ef5983fcef85b3be8cebbe5c7538f74dea65c97f"
      define_method(:install) do
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tq-lang/tq/releases/download/v0.1.0-rc10/tq_0.1.0-rc10_linux_arm64.tar.gz"
      sha256 "71b498ae23071d95e4adf18c229edaa861a77924e8f2ee4c7ad4c9a290938864"
      define_method(:install) do
        bin.install "tq"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tq --version")
  end
end
